### ISSUE TITLE
Error importing key into GnuPG 2.2.4 on Ubuntu 18.04

### ISSUE THREAD

**Issue by DefProc** [fluidkeys/fluidkeys#273]
- Fluidkeys version number or commit hash: `0.3.1`
- Your operating system: `Ubuntu 18.04`
- Your GnuPG version: `gpg (GnuPG) 2.2.4`, `libgcrypt 1.8.1`

Just got this error at the "Finishing Setup" stage of `fk setup`. What's my next move?

```
 Finishing setup                                                                

🛠️  Carrying out the following tasks:

    [✔] Generate key for <username@example.com>
panic: error pushing key back to gpg: problem importing key, gpg failed with error 'exit status 2'

goroutine 1 [running]:
log.Panicf(0x8602a4, 0x21, 0xc420069c20, 0x1, 0x1)
	/usr/lib/go-1.10/src/log/log.go:333 +0xda
main.keyCreate(0xc4202d13a0, 0x15, 0x110, 0x8466d5)
	/tmp/tmp.MGeioLevsh/src/github.com/fluidkeys/fluidkeys/fluidkeys/keycreate.go:167 +0xd0a
main.setup(0x0, 0x0, 0x84af1e)
	/tmp/tmp.MGeioLevsh/src/github.com/fluidkeys/fluidkeys/fluidkeys/setup.go:21 +0x173
main.setupSubcommand(0xc4201a4840, 0xc4201a4bd0)
	/tmp/tmp.MGeioLevsh/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:265 +0x1b6
main.main()
	/tmp/tmp.MGeioLevsh/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:95 +0x2f5
```

**Comment by paulfurley** [comment]
Ouch. Thanks for reporting this @DefProc.
I've been dreading the day where I had to remotely debug problems fk / gpg interaction! I'll get back to you...

**Comment by DefProc** [comment]
of course: 

```
 Finishing setup                                                                

🛠️  Carrying out the following tasks:

    [✔] Generate key for <username@example.com>
panic: error pushing key back to gpg: exit status 2, stderr: gpg: armour: BEGIN PGP PUBLIC KEY BLOCK [see fluidkeys log for more]

goroutine 1 [running]:
log.Panicf(0x860270, 0x21, 0xc420069c00, 0x1, 0x1)
	/usr/lib/go-1.10/src/log/log.go:333 +0xda
main.keyCreate(0xc4202d0f40, 0x15, 0x110, 0x8466d5)
	/tmp/tmp.2MHkPjIcjh/src/github.com/fluidkeys/fluidkeys/fluidkeys/keycreate.go:167 +0xd0a
main.setup(0x0, 0x0, 0x84af1d)
	/tmp/tmp.2MHkPjIcjh/src/github.com/fluidkeys/fluidkeys/fluidkeys/setup.go:21 +0x173
main.setupSubcommand(0xc420166720, 0xc4201668d0)
	/tmp/tmp.2MHkPjIcjh/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:267 +0x1b6
main.main()
	/tmp/tmp.2MHkPjIcjh/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:97 +0x352
```

Where is the fluidkey's log location? I'm happy to see if there's more detail there…

**Comment by paulfurley** [comment]
`~/.config/fluidkeys/debug.log ` - thanks!

**Comment by DefProc** [comment]
```
2019/01/11 15:31:18 Enter the 2nd word from your password
2019/01/11 15:31:18 [2nd word] : 
2019/01/11 15:31:24  Verify your email                                                              
2019/01/11 15:31:24 You should have received a confirmation link emailed to username@example.com.
2019/01/11 15:31:24 Waiting for link to be clicked...
2019/01/11 15:31:29 error polling api for public key: Public key not found
2019/01/11 15:31:34  ▸   Successfully verified email address
2019/01/11 15:31:34  Finishing setup                                                                
2019/01/11 15:31:34 🛠️  Carrying out the following tasks:
2019/01/11 15:31:34     [✔] Generate key for username@example.com
2019/01/11 15:31:34 command failed: `gpg -vv --keyid-format 0xlong --batch --no-tty --import` : exit status 2
2019/01/11 15:31:34 gpg: armour: BEGIN PGP PUBLIC KEY BLOCK
2019/01/11 15:31:34 # off=0 ctb=c6 tag=6 hlen=3 plen=525 new-ctb
2019/01/11 15:31:34 :public key packet:
2019/01/11 15:31:34 	version 4, algo 1, created 1547220641, expires 0
2019/01/11 15:31:34 	pkey[0]: [4096 bits]
2019/01/11 15:31:34 	pkey[1]: [17 bits]
2019/01/11 15:31:34 	keyid: B206715205E186C5
2019/01/11 15:31:34 # off=528 ctb=cd tag=13 hlen=2 plen=23 new-ctb
2019/01/11 15:31:34 :user ID packet: "<username@example.com>"
2019/01/11 15:31:34 # off=553 ctb=c2 tag=2 hlen=3 plen=569 new-ctb
2019/01/11 15:31:34 :signature packet: algo 1, keyid B206715205E186C5
2019/01/11 15:31:34 	version 4, created 1547220641, md5len 0, sigclass 0x13
2019/01/11 15:31:34 	digest algo 10, begin of digest c1 b2
2019/01/11 15:31:34 	hashed subpkt 2 len 4 (sig created 2019-01-11)
2019/01/11 15:31:34 	hashed subpkt 16 len 8 (issuer key ID B206715205E186C5)
2019/01/11 15:31:34 	hashed subpkt 27 len 1 (key flags: 03)
2019/01/11 15:31:34 	hashed subpkt 9 len 4 (key expires after 50d8h29m)
2019/01/11 15:31:34 	hashed subpkt 25 len 1 (primary user ID)
2019/01/11 15:31:34 	hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 3)
2019/01/11 15:31:34 	hashed subpkt 21 len 4 (pref-hash-algos: 10 9 8 11)
2019/01/11 15:31:34 	hashed subpkt 22 len 3 (pref-zip-algos: 2 1 0)
2019/01/11 15:31:34 	data: [4095 bits]
2019/01/11 15:31:34 # off=1125 ctb=ce tag=14 hlen=3 plen=269 new-ctb
2019/01/11 15:31:34 :public sub key packet:
2019/01/11 15:31:34 	version 4, algo 1, created 1547220641, expires 0
2019/01/11 15:31:34 	pkey[0]: [2048 bits]
2019/01/11 15:31:34 	pkey[1]: [17 bits]
2019/01/11 15:31:34 	keyid: 3866F52404D53B28
2019/01/11 15:31:34 # off=1397 ctb=c2 tag=2 hlen=3 plen=549 new-ctb
2019/01/11 15:31:34 :signature packet: algo 1, keyid B206715205E186C5
2019/01/11 15:31:34 	version 4, created 1547220641, md5len 0, sigclass 0x18
2019/01/11 15:31:34 	digest algo 10, begin of digest 81 a9
2019/01/11 15:31:34 	hashed subpkt 2 len 4 (sig created 2019-01-11)
2019/01/11 15:31:34 	hashed subpkt 16 len 8 (issuer key ID B206715205E186C5)
2019/01/11 15:31:34 	hashed subpkt 27 len 1 (key flags: 0C)
2019/01/11 15:31:34 	hashed subpkt 9 len 4 (key expires after 50d8h29m)
2019/01/11 15:31:34 	data: [4095 bits]
2019/01/11 15:31:34 gpg: pub  rsa4096/0xB206715205E186C5 2019-01-11  <username@example.com>
2019/01/11 15:31:34 gpg: no writable keyring found: Not found
2019/01/11 15:31:34 gpg: error reading '[stdin]': General error
2019/01/11 15:31:34 gpg: import from '[stdin]' failed: General error
2019/01/11 15:31:34 gpg: Total number processed: 0
2019/01/11 15:31:34 error pushing key back to gpg: exit status 2, stderr: gpg: armour: BEGIN PGP PUBLIC KEY BLOCK [see fluidkeys log for more]
2019/01/11 15:32:30 found working gpg2 with version '2.2.4': /usr/bin/gpg2
2019/01/11 15:32:30 $ fk log
```

(with a valid email address in the actual log)

**Comment by paulfurley** [comment]
Wonderful, thanks!

**Comment by paulfurley** [comment]
@DefProc Strange error `gpg: no writable keyring found: Not found`  Couple of questions:

* What does `gpg --help | grep Home` show?
* Does that directory exist?
* If it doesn't exist, are there permissions on your home directory that would prevent that directory from being created by gpg?

**Comment by paulfurley** [comment]
Hey @DefProc when you've got 5 minutes it would be mega helpful if you could take a look ^^ Thanks!

**Comment by DefProc** [comment]
Sorry, didn't the the previous reply! :smile: 

 * `gpg --help | grep Home` = `Home: /home/username/.gnupg`
 * `echo $GNUPGHOME` = ` `(empty response)
 * `ll ~/.gnupg` = 

```
total 200
drwx------  4 username username  4096 Nov 19 12:10 ./
drwxr-xr-x 56 username username  4096 Jan 15 17:34 ../
drwx------  2 username username  4096 Jun  4  2018 crls.d/
drwx------  2 username username  4096 Apr 30  2018 private-keys-v1.d/
-rw-r--r--  1 root     root     81129 Oct  1 17:05 pubring.kbx
-rw-rw-r--  1 username username 46807 Jun  4  2018 pubring.kbx~
-rw-------  1 username username   600 May  8  2018 random_seed
-rw-r--r--  1 username username 49152 Jun  4  2018 tofu.db
-rw-------  1 username username  1200 Oct  1 17:05 trustdb.gpg
```

 * no `~/.gnupg/pubring.gpg` file
 * `curl https://www.fluidkeys.com/release.asc | gpg --import`=

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1680  100  1680    0     0   7058      0 --:--:-- --:--:-- --:--:--  7088
gpg: no writable keyring found: Not found
gpg: error reading '[stdin]': General error
gpg: import from '[stdin]' failed: General error
gpg: Total number processed: 0
```

Is this a problem of a missing keyring file?

**Comment by paulfurley** [comment]
Ah-hah!

Your `pubring.kbx` is owned by `root`, which breaks your GnuPG (it can't modify its own list of public keys).

This'll fix it:
```
sudo chmod username:username /home/username/.gnupg/pubring.kbx
```

**Comment by DefProc** [comment]
Cool, ta.

Although it now fails earlier with: 

```
 Verify your email                                                              

You should have received a confirmation link emailed to username@example.com.

  Waiting for you to click the link ⠏panic: Failed to get public key: Retrieved key's fingerprint doesn't match

goroutine 1 [running]:
log.Panicf(0x85d2b0, 0x1c, 0xc420069c10, 0x1, 0x1)
	/usr/lib/go-1.10/src/log/log.go:333 +0xda
main.keyCreate(0x7ffe0a46445b, 0x15, 0x110, 0x8466d5)
	/tmp/tmp.2MHkPjIcjh/src/github.com/fluidkeys/fluidkeys/fluidkeys/keycreate.go:142 +0xb39
main.setup(0x7ffe0a46445b, 0x15, 0x1)
	/tmp/tmp.2MHkPjIcjh/src/github.com/fluidkeys/fluidkeys/fluidkeys/setup.go:21 +0x173
main.setupSubcommand(0xc4201713e0, 0xc420171590)
	/tmp/tmp.2MHkPjIcjh/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:277 +0x105
main.main()
	/tmp/tmp.2MHkPjIcjh/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:97 +0x352
```

Is this because I need to reset something locally?

**Comment by paulfurley** [comment]
Ack, sorry about that. It's a horrible way of Fluidkeys saying "you've already got a verified key".

I've just reset your email, so it should work now.

**Comment by DefProc** [comment]
Nice, all setup!

**Comment by paulfurley** [comment]
boom, thanks very much for your patience!
