### ISSUE TITLE
Error import key into gpg on Ubuntu 16.04

### ISSUE THREAD

**Issue by paulfurley** [fluidkeys/fluidkeys#278]
- Fluidkeys 0.3.2
- Ubuntu 16.04
- gpg 2.1.11

```
panic: error pushing key back to gpg: problem importing key, gpg failed with error 'exit status 2'

goroutine 1 [running]:

log.Panicf(0x8602a4, 0x21, 0xc420067c20, 0x1, 0x1)
        /usr/lib/go-1.10/src/log/log.go:333 +0xda
main.keyCreate(0xc420297020, 0x13, 0x110, 0x8466d5)
        /tmp/tmp.MGeioLevsh/src/github.com/fluidkeys/fluidkeys/fluidkeys/keycreate.go:167 +0xd0a
main.setup(0x0, 0x0, 0x84af1e)
        /tmp/tmp.MGeioLevsh/src/github.com/fluidkeys/fluidkeys/fluidkeys/setup.go:21 +0x173
main.setupSubcommand(0xc42015c870, 0xc42015ce40)
        /tmp/tmp.MGeioLevsh/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:265 +0x1b6
main.main()
        /tmp/tmp.MGeioLevsh/src/github.com/fluidkeys/fluidkeys/fluidkeys/main.go:95 +0x2f5
```

**Comment by paulfurley** [comment]
I *think* this might be a permissions problem preventing `gpg` from creating or editing `~/.gnupg/pubring.gpg`

**Comment by paulfurley** [comment]
Haven't been able to reproduce and haven't had any further input from the original reporter yet, so I'm going to close this for now.
